import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { api, setApiKey } from '../api'
import { Failure, Loading } from '../components/State'
type Settings={version:string;auth:{enabled:boolean};ai:{enabled:boolean;model:string;prompt_version:string};channels:Record<string,boolean>;worker_concurrency:number}
export default function SettingsPage(){
 const query=useQuery({queryKey:['settings'],queryFn:()=>api<{data:Settings}>('/settings')}),[key,setKey]=useState('')
 if(query.isLoading)return <Loading/>;if(query.error)return <Failure error={query.error}/>
 const value=query.data!.data
 return <div className="space-y-6"><div><div className="mb-2 flex items-center gap-3"><h1>Settings</h1><span className="badge">{value.version}</span></div><p className="muted">Runtime state only. Secrets are never returned by the API.</p></div><section className="panel"><div className="flex items-center justify-between gap-4"><div><h2>Console access</h2><p className="muted mt-1">{value.auth.enabled?'API-key protection is enabled for this deployment.':'Local access mode is enabled. No sign-in is required.'}</p></div><span className={`badge ${value.auth.enabled?'':'text-emerald-300'}`}>{value.auth.enabled?'Protected':'Local mode'}</span></div>{value.auth.enabled&&<div className="mt-4 flex gap-3"><input className="field" type="password" autoComplete="off" placeholder="Enter a new API key" value={key} onChange={e=>setKey(e.target.value)}/><button className="btn" disabled={!key.trim()} onClick={()=>{setApiKey(key);setKey('');query.refetch()}}>Use for this tab</button></div>}</section><section className="panel"><h2>Provider readiness</h2><div className="mt-5 grid gap-3 sm:grid-cols-3">{Object.entries(value.channels).map(([name,ready])=><div className="rounded-xl border border-white/8 p-4" key={name}><div className="flex items-center justify-between"><b className="capitalize">{name}</b><span className={`size-2 rounded-full ${ready?'bg-emerald-400':'bg-slate-600'}`}/></div><p className="muted mt-2">{ready?'Configured':'Unavailable'}</p></div>)}</div></section><section className="panel"><h2>AI analysis</h2><dl className="mt-4 grid gap-4 sm:grid-cols-3"><div><dt className="muted">Status</dt><dd>{value.ai.enabled?'Enabled':'Fallback only'}</dd></div><div><dt className="muted">Model</dt><dd>{value.ai.model}</dd></div><div><dt className="muted">Prompt</dt><dd>{value.ai.prompt_version}</dd></div></dl></section></div>
}
